FROM gcr.io/tensorflow/tensorflow:latest-gpu

MAINTAINER Rodrigo Silva <rbsilva.ti@gmail.com>

RUN pip install scikit-learn
RUN pip install Pillow
RUN pip install beautifulsoup4
RUN pip install pandas
RUN pip install keras
RUN pip install tflearn
RUN pip install tpot
RUN pip install deap
RUN pip install vpython
RUN pip install spacy
RUN pip install kanren
